trigger:
  none

pool:
  vmImage: 'ubuntu-latest'

# variables:
# - group: vault-secrets  # Name of your variable group
#   steps:
#   - script: echo "Varible group scret is $(client-id)"
# #   resource_group_name: 'openenv-rrv2r-1'
#   cluster_name: 'test-cluster'
#   node_count: '3'
#   node_vm_size: 'Standard_D2s_v5'

stages:
- stage: Terraform_Installation
  displayName: 'Terraform Installation on the Agent Stage'
  jobs:
  - job: terraform_install
    displayName: 'Terraform Installation Job'
    steps:
    # - task: AzureKeyVault@2
    #   inputs:
    #     azureSubscription: 'azure-test' # Your service connection name
    #     KeyVaultName: 'test-kv'
    #     SecretsFilter: '*'          # Use '*' for all or 'secret1,secret2' for specific ones
    #     RunAsPreJob: false          # Set to true to make secrets available to all jobs

    - checkout: self
      persistCredentials: true

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.6.6'
    - task: AzureCLI@2
      displayName: 'Fetch Backend Details'
      inputs:
      azureSubscription: 'your-service-connection-name'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Find account starting with 'store'
        RG_NAME=$(az group list --query "[?starts_with(name, 'nebula') || starts_with(name, 'openenv')].name | [0]" -o tsv)
        STORAGE_ACC = $(az storage account list -g $(resourceGroupName) --query "[?starts_with(name, 'store')].name | [0]" -o tsv)    
        CONTAINER=$(az storage container list --account-name $STORAGE_ACC --auth-mode login --query "[?name=='tfstate'].name | [0]" -o tsv)
      

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        # The path to where your .tf files are (e.g., $(System.DefaultWorkingDirectory)/aks)
        workingDirectory: '$(System.DefaultWorkingDirectory)/aks' 
      
      # Backend Configuration
        backendServiceArm: 'azure-test' 
        backendAzureRmResourceGroupName: '$(RG_NAME)' # Put your connection name here
        backendAzureRmStorageAccountName: '$(STORAGE_ACC)'
        backendAzureRmContainerName: '$(CONTAINER)' 
        backendAzureRmKey: 'dev.terraform.tfstate'
       # 4. Plan
    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/aks'
        environmentServiceNameAzureRM: 'azure-test'
        # PASSING SECRETS: Map your KV secret names to Terraform variables here
        #commandOptions: '-var="client_secret=$(client-secret)" -var="client_id=$(client-id)" -var="tenant_id=$(tenant-id)" -var="subscription_id=$(subscription-id)"'

    # 5. Apply
    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/aks'
        environmentServiceNameAzureRM: 'azure-test'
        # Ensure apply uses the same variables
        #commandOptions: '-auto-approve -var="client_secret=$(client-secret)" -var="client_id=$(client-id)" -var="tenant_id=$(tenant-id)" -var="subscription_id=$(subscription-id)"'