trigger:
  none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: vault-secrets  # Name of your variable group
#   steps:
#   - script: echo "Varible group scret is $(client-id)"
# #   resource_group_name: 'openenv-rrv2r-1'
#   cluster_name: 'test-cluster'
#   node_count: '3'
#   node_vm_size: 'Standard_D2s_v5'

stages:
- stage: Terraform_Installation
  displayName: 'Terraform Installation on the Agent Stage'
  jobs:
  - job: terraform_install
    displayName: 'Terraform Installation Job'
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'redhat-test' # Your service connection name
        KeyVaultName: 'test-kv-2026011'
        SecretsFilter: '*'          # Use '*' for all or 'secret1,secret2' for specific ones
        RunAsPreJob: false          # Set to true to make secrets available to all jobs

    - checkout: self
      persistCredentials: true

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.6.6'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        # The path to where your .tf files are (e.g., $(System.DefaultWorkingDirectory)/aks)
        workingDirectory: '$(System.DefaultWorkingDirectory)/aks' 
      
      # Backend Configuration
        backendServiceArm: 'redhat-test' # Put your connection name here
        backendAzureRmResourceGroupName: 'openenv-rrv2r-1'
        backendAzureRmStorageAccountName: 'store202602'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.terraform.tfstate'
       # 4. Plan
    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/aks'
        environmentServiceNameAzureRM: 'redhat-test'
        # PASSING SECRETS: Map your KV secret names to Terraform variables here
        #commandOptions: '-var="client_secret=$(client-secret)" -var="client_id=$(client-id)" -var="tenant_id=$(tenant-id)" -var="subscription_id=$(subscription-id)"'

    # 5. Apply
    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/aks'
        environmentServiceNameAzureRM: 'redhat-test'
        # Ensure apply uses the same variables
        #commandOptions: '-auto-approve -var="client_secret=$(client-secret)" -var="client_id=$(client-id)" -var="tenant_id=$(tenant-id)" -var="subscription_id=$(subscription-id)"'