trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Adjust for your environment or set in DevOps Library
  location: 'eastus'
  resource_group_name: 'openenv-rrv2r-1'
  cluster_name: 'test-cluster'
  node_count: '3'
  node_vm_size: 'Standard_D2s_v5'

stages:
- stage: Terraform
  displayName: 'Terraform AKS'
  jobs:
  - job: plan_apply
    displayName: 'Plan & Apply'
    steps:
    - checkout: self
      persistCredentials: true

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.6.6'