trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: vault-secrets  # Name of your variable group
steps:
- script: echo "Varible group scret is $(client-id)"
#   resource_group_name: 'openenv-rrv2r-1'
#   cluster_name: 'test-cluster'
#   node_count: '3'
#   node_vm_size: 'Standard_D2s_v5'

stages:
- stage: Terraform Installation
  displayName: 'Terraform Installation on the Agent Stage'
  jobs:
  - job: terraform_install
    displayName: 'Terraform Installation Job'
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'redhat-test' # Your service connection name
        KeyVaultName: 'test-kv-2026011'
        SecretsFilter: '*'          # Use '*' for all or 'secret1,secret2' for specific ones
        RunAsPreJob: false          # Set to true to make secrets available to all jobs

    - script: echo "The secret is from task  $(client-secret)"
      displayName: 'Use Secret'
    

    - checkout: self
      persistCredentials: true

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.6.6'
