trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Adjust for your environment or set in DevOps Library
  location: 'eastus'
  resource_group_name: 'openenv-rrv2r-1'
  cluster_name: 'test-cluster'
  node_count: '3'
  node_vm_size: 'Standard_D2s_v5'

  # Remote backend for Terraform state
  tfstate_resource_group: 'rg-tfstate'
  tfstate_storage_account: 'sttfstate20260209'
  tfstate_container: 'tfstate'

stages:
- stage: Terraform
  displayName: 'Terraform AKS'
  jobs:
  - job: plan_apply
    displayName: 'Plan & Apply'
    steps:
    - checkout: self
      persistCredentials: true

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.6.6'

    - task: TerraformTaskV4@4
      name: init
      displayName: 'terraform init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'aks'
        backendServiceArm: 'redhat-test'
        backendAzureRmResourceGroupName: '$(tfstate_resource_group)'
        backendAzureRmStorageAccountName: '$(tfstate_storage_account)'
        backendAzureRmContainerName: '$(tfstate_container)'
        backendAzureRmKey: 'aks/test-cluster.tfstate'

    - task: TerraformTaskV4@4
      name: plan
      displayName: 'terraform plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: 'aks'
        environmentServiceNameAzureRM: 'redhat-test'
        commandOptions: >
          -var="location=$(location)"
          -var="resource_group_name=$(resource_group_name)"
          -var="cluster_name=$(cluster_name)"
          -var="node_count=$(node_count)"
          -var="node_vm_size=$(node_vm_size)"
          -var="tfstate_resource_group=$(tfstate_resource_group)"
          -var="tfstate_storage_account=$(tfstate_storage_account)"
          -var="tfstate_container=$(tfstate_container)"
        allowTelemetryCollection: false

    # Optional: Approvals via environments before apply
    - task: TerraformTaskV4@4
      name: apply
      displayName: 'terraform apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: 'aks'
        environmentServiceNameAzureRM: 'redhat-test'
        commandOptions: >
          -auto-approve
          -var="location=$(location)"
          -var="resource_group_name=$(resource_group_name)"
          -var="cluster_name=$(cluster_name)"
          -var="node_count=$(node_count)"
          -var="node_vm_size=$(node_vm_size)"
          -var="tfstate_resource_group=$(tfstate_resource_group)"
          -var="tfstate_storage_account=$(tfstate_storage_account)"
          -var="tfstate_container=$(tfstate_container)"
        allowTelemetryCollection: false

    # Save outputs as pipeline artifacts (kubeconfig & ssh key) – handle with care!
    - bash: |
        set -e
        echo "Extracting outputs..."
        terraform -chdir=terraform output -raw kube_user_config > kubeconfig
        terraform -chdir=terraform output -raw ssh_private_key_pem > id_rsa
        chmod 600 id_rsa
        echo "Files produced: kubeconfig, id_rsa"
      displayName: 'Export sensitive outputs'
    - publish: kubeconfig
      artifact: kubeconfig
      displayName: 'Publish kubeconfig (sensitive)'
    - publish: id_rsa
      artifact: id_rsa
      displayName: 'Publish SSH key (sensitive)'